[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = esp8266-rtos-sdk

; 清理掉之前的错误缓存配置
build_unflags = -I"C:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\include\freertos"

; 强制注入最全的系统头文件路径
build_flags = 
    -I"C:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\include"
    -I"C:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\include\esp8266"
    -I"C:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\include\freertos"
    -LC:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\lib
    -lnet80211 -lpp -lwpa -lphy -lmain

board_build.f_cpu = 80000000L
board_build.flash_mode = dio
upload_speed = 115200
monitor_speed = 74880