[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = esp8266-rtos-sdk

; 💡 终极完全体：前半段负责跟静态库肉搏（维持编译通过），后半段负责给 VS Code 插件指路（消灭红线）
build_flags = 
    -LC:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\lib
    -lnet80211
    -lpp
    -lwpa
    -lphy
    -lmain
    -IC:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\include\freertos
    -IC:\Users\jj155\.platformio\packages\framework-esp8266-rtos-sdk\include\freertos\freertos

; 物理硬核参数打桩
board_build.f_cpu = 80000000L
board_build.flash_mode = dio
upload_speed = 115200
monitor_speed = 74880

